# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ticket_reservation_pb2 as ticket__reservation__pb2


class TicketReservationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReserveTicket = channel.unary_unary(
                '/ticket_reservation.TicketReservation/ReserveTicket',
                request_serializer=ticket__reservation__pb2.ReservationRequest.SerializeToString,
                response_deserializer=ticket__reservation__pb2.ReservationResponse.FromString,
                )
        self.ModifyTicket = channel.unary_unary(
                '/ticket_reservation.TicketReservation/ModifyTicket',
                request_serializer=ticket__reservation__pb2.ReservationRequest.SerializeToString,
                response_deserializer=ticket__reservation__pb2.ReservationResponse.FromString,
                )
        self.CancelTicket = channel.unary_unary(
                '/ticket_reservation.TicketReservation/CancelTicket',
                request_serializer=ticket__reservation__pb2.ReservationRequest.SerializeToString,
                response_deserializer=ticket__reservation__pb2.ReservationResponse.FromString,
                )


class TicketReservationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReserveTicket(self, request, context):
        """A simple RPC.

        Obtains the MessageResponse at a given position.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TicketReservationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReserveTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveTicket,
                    request_deserializer=ticket__reservation__pb2.ReservationRequest.FromString,
                    response_serializer=ticket__reservation__pb2.ReservationResponse.SerializeToString,
            ),
            'ModifyTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyTicket,
                    request_deserializer=ticket__reservation__pb2.ReservationRequest.FromString,
                    response_serializer=ticket__reservation__pb2.ReservationResponse.SerializeToString,
            ),
            'CancelTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTicket,
                    request_deserializer=ticket__reservation__pb2.ReservationRequest.FromString,
                    response_serializer=ticket__reservation__pb2.ReservationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ticket_reservation.TicketReservation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TicketReservation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReserveTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ticket_reservation.TicketReservation/ReserveTicket',
            ticket__reservation__pb2.ReservationRequest.SerializeToString,
            ticket__reservation__pb2.ReservationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ModifyTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ticket_reservation.TicketReservation/ModifyTicket',
            ticket__reservation__pb2.ReservationRequest.SerializeToString,
            ticket__reservation__pb2.ReservationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ticket_reservation.TicketReservation/CancelTicket',
            ticket__reservation__pb2.ReservationRequest.SerializeToString,
            ticket__reservation__pb2.ReservationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
