# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ticket_reservation.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18ticket_reservation.proto\x12\x12ticket_reservation\"t\n\x0cuser_details\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\x0c\n\x04seat\x18\x05 \x01(\r\x12\x0f\n\x07section\x18\x06 \x01(\t\"\xc1\x01\n\x12ReservationRequest\x12\x16\n\tticket_no\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x11\n\tfrom_code\x18\x02 \x01(\t\x12\x0f\n\x07to_code\x18\x03 \x01(\t\x12\x12\n\nprice_paid\x18\x04 \x01(\x04\x12\x17\n\x0fpassenger_count\x18\x05 \x01(\x04\x12\x34\n\npassengers\x18\x06 \x03(\x0b\x32 .ticket_reservation.user_detailsB\x0c\n\n_ticket_no\"\xbf\x01\n\x13ReservationResponse\x12\x11\n\tticket_no\x18\x01 \x01(\x04\x12\x11\n\tfrom_code\x18\x02 \x01(\t\x12\x0f\n\x07to_code\x18\x03 \x01(\t\x12\x12\n\nprice_paid\x18\x04 \x01(\x04\x12\x17\n\x0fpassenger_count\x18\x05 \x01(\x04\x12\x34\n\npassengers\x18\x06 \x03(\x0b\x32 .ticket_reservation.user_details\x12\x0e\n\x06status\x18\x07 \x01(\t2\xbd\x02\n\x11TicketReservation\x12\x62\n\rReserveTicket\x12&.ticket_reservation.ReservationRequest\x1a\'.ticket_reservation.ReservationResponse\"\x00\x12\x61\n\x0cModifyTicket\x12&.ticket_reservation.ReservationRequest\x1a\'.ticket_reservation.ReservationResponse\"\x00\x12\x61\n\x0c\x43\x61ncelTicket\x12&.ticket_reservation.ReservationRequest\x1a\'.ticket_reservation.ReservationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ticket_reservation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER_DETAILS']._serialized_start=48
  _globals['_USER_DETAILS']._serialized_end=164
  _globals['_RESERVATIONREQUEST']._serialized_start=167
  _globals['_RESERVATIONREQUEST']._serialized_end=360
  _globals['_RESERVATIONRESPONSE']._serialized_start=363
  _globals['_RESERVATIONRESPONSE']._serialized_end=554
  _globals['_TICKETRESERVATION']._serialized_start=557
  _globals['_TICKETRESERVATION']._serialized_end=874
# @@protoc_insertion_point(module_scope)
